privateKey: 'YOUR_PRIVATE_KEY_STARTING_WITH_0X'
target: 'DESTINATION_ADDRESS'
tokens:
  - symbol: DAI
    addr: '0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa'
    amount: '0.00001'
  - symbol: DAI
    addr: '0x4F96Fe3b7A6Cf9725f59d353F723c1bDb64CA6Aa'
    amount: '0.00002'

ethNode: wss://eth-kovan.ws.alchemyapi.io/v2/XXXXXXXXXXXXXXXX
